// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/livepeerai/models/components"
)

type AudioToTextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TextResponse *components.TextResponse
}

func (o *AudioToTextResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AudioToTextResponse) GetTextResponse() *components.TextResponse {
	if o == nil {
		return nil
	}
	return o.TextResponse
}
