// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenImageToVideoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	VideoResponse *components.VideoResponse
}

func (g *GenImageToVideoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenImageToVideoResponse) GetVideoResponse() *components.VideoResponse {
	if g == nil {
		return nil
	}
	return g.VideoResponse
}
