// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenImageToTextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ImageToTextResponse *components.ImageToTextResponse
}

func (g *GenImageToTextResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenImageToTextResponse) GetImageToTextResponse() *components.ImageToTextResponse {
	if g == nil {
		return nil
	}
	return g.ImageToTextResponse
}
