// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenLLMResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	LLMResponse *components.LLMResponse
}

func (g *GenLLMResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenLLMResponse) GetLLMResponse() *components.LLMResponse {
	if g == nil {
		return nil
	}
	return g.LLMResponse
}
