// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenLiveVideoToVideoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	LiveVideoToVideoResponse *components.LiveVideoToVideoResponse
}

func (g *GenLiveVideoToVideoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenLiveVideoToVideoResponse) GetLiveVideoToVideoResponse() *components.LiveVideoToVideoResponse {
	if g == nil {
		return nil
	}
	return g.LiveVideoToVideoResponse
}
