// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenLiveVideoToVideoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	LiveVideoToVideoResponse *components.LiveVideoToVideoResponse
}

func (o *GenLiveVideoToVideoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GenLiveVideoToVideoResponse) GetLiveVideoToVideoResponse() *components.LiveVideoToVideoResponse {
	if o == nil {
		return nil
	}
	return o.LiveVideoToVideoResponse
}
