// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-ai-go/models/components"
)

type GenSegmentAnything2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	MasksResponse *components.MasksResponse
}

func (g *GenSegmentAnything2Response) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenSegmentAnything2Response) GetMasksResponse() *components.MasksResponse {
	if g == nil {
		return nil
	}
	return g.MasksResponse
}
