// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/my-company/livepeerai/models/components"
)

type TextToImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ImageResponse *components.ImageResponse
}

func (o *TextToImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TextToImageResponse) GetImageResponse() *components.ImageResponse {
	if o == nil {
		return nil
	}
	return o.ImageResponse
}
