// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/livepeer/livepeer-ai-go/models/components"
)

// HTTPError - HTTP error response model.
type HTTPError struct {
	// Detailed error information.
	Detail components.APIError `json:"detail"`
}

var _ error = &HTTPError{}

func (e *HTTPError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
