// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// APIError - API error response model.
type APIError struct {
	// The error message.
	Msg string `json:"msg"`
}

func (a *APIError) GetMsg() string {
	if a == nil {
		return ""
	}
	return a.Msg
}
