// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APIError struct {
	Msg string `json:"msg"`
}

func (o *APIError) GetMsg() string {
	if o == nil {
		return ""
	}
	return o.Msg
}
