// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AudioResponse - Response model for audio generation.
type AudioResponse struct {
	// The generated audio.
	Audio MediaURL `json:"audio"`
}

func (o *AudioResponse) GetAudio() MediaURL {
	if o == nil {
		return MediaURL{}
	}
	return o.Audio
}
