// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-ai-go/internal/utils"
)

type BodyUpscaleUpscalePostImage struct {
	FileName string `multipartForm:"name=image"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (o *BodyUpscaleUpscalePostImage) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *BodyUpscaleUpscalePostImage) GetContent() any {
	if o == nil {
		return nil
	}
	return o.Content
}

type BodyUpscaleUpscalePost struct {
	// Text prompt(s) to guide upscaled image generation.
	Prompt string `multipartForm:"name=prompt"`
	// Uploaded image to modify with the pipeline.
	Image BodyUpscaleUpscalePostImage `multipartForm:"file"`
	// Hugging Face model ID used for upscaled image generation.
	ModelID *string `default:"" multipartForm:"name=model_id"`
	// Perform a safety check to estimate if generated images could be offensive or harmful.
	SafetyCheck *bool `default:"true" multipartForm:"name=safety_check"`
	// Seed for random number generation.
	Seed *int64 `multipartForm:"name=seed"`
	// Number of denoising steps. More steps usually lead to higher quality images but slower inference. Modulated by strength.
	NumInferenceSteps *int64 `default:"75" multipartForm:"name=num_inference_steps"`
}

func (b BodyUpscaleUpscalePost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyUpscaleUpscalePost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BodyUpscaleUpscalePost) GetPrompt() string {
	if o == nil {
		return ""
	}
	return o.Prompt
}

func (o *BodyUpscaleUpscalePost) GetImage() BodyUpscaleUpscalePostImage {
	if o == nil {
		return BodyUpscaleUpscalePostImage{}
	}
	return o.Image
}

func (o *BodyUpscaleUpscalePost) GetModelID() *string {
	if o == nil {
		return nil
	}
	return o.ModelID
}

func (o *BodyUpscaleUpscalePost) GetSafetyCheck() *bool {
	if o == nil {
		return nil
	}
	return o.SafetyCheck
}

func (o *BodyUpscaleUpscalePost) GetSeed() *int64 {
	if o == nil {
		return nil
	}
	return o.Seed
}

func (o *BodyUpscaleUpscalePost) GetNumInferenceSteps() *int64 {
	if o == nil {
		return nil
	}
	return o.NumInferenceSteps
}
