// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-ai-go/internal/utils"
)

type Audio struct {
	FileName string `multipartForm:"name=audio"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (o *Audio) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *Audio) GetContent() any {
	if o == nil {
		return nil
	}
	return o.Content
}

type BodyAudioToTextAudioToTextPost struct {
	// Uploaded audio file to be transcribed.
	Audio Audio `multipartForm:"file"`
	// Hugging Face model ID used for transcription.
	ModelID *string `default:"" multipartForm:"name=model_id"`
}

func (b BodyAudioToTextAudioToTextPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyAudioToTextAudioToTextPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BodyAudioToTextAudioToTextPost) GetAudio() Audio {
	if o == nil {
		return Audio{}
	}
	return o.Audio
}

func (o *BodyAudioToTextAudioToTextPost) GetModelID() *string {
	if o == nil {
		return nil
	}
	return o.ModelID
}
