// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Chunk struct {
	Timestamp []any  `json:"timestamp"`
	Text      string `json:"text"`
}

func (o *Chunk) GetTimestamp() []any {
	if o == nil {
		return []any{}
	}
	return o.Timestamp
}

func (o *Chunk) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
