// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Chunk - A chunk of text with a timestamp.
type Chunk struct {
	// The timestamp of the chunk.
	Timestamp []float64 `json:"timestamp"`
	// The text of the chunk.
	Text string `json:"text"`
}

func (o *Chunk) GetTimestamp() []float64 {
	if o == nil {
		return []float64{}
	}
	return o.Timestamp
}

func (o *Chunk) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
