// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ImageToTextResponse - Response model for text generation.
type ImageToTextResponse struct {
	// The generated text.
	Text string `json:"text"`
}

func (o *ImageToTextResponse) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
