// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ImageResponse struct {
	Images []Media `json:"images"`
}

func (o *ImageResponse) GetImages() []Media {
	if o == nil {
		return []Media{}
	}
	return o.Images
}
