// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-ai-go/internal/utils"
)

// Params - Initial parameters for the pipeline.
type Params struct {
}

type LiveVideoToVideoParams struct {
	// Source URL of the incoming stream to subscribe to.
	SubscribeURL string `json:"subscribe_url"`
	// Destination URL of the outgoing stream to publish.
	PublishURL string `json:"publish_url"`
	// URL for subscribing via Trickle protocol for updates in the live video-to-video generation params.
	ControlURL *string `default:"" json:"control_url"`
	// URL for publishing events via Trickle protocol for pipeline status and logs.
	EventsURL *string `default:"" json:"events_url"`
	// Name of the pipeline to run in the live video to video job. Notice that this is named model_id for consistency with other routes, but it does not refer to a Hugging Face model ID. The exact model(s) depends on the pipeline implementation and might be configurable via the `params` argument.
	ModelID *string `default:"" json:"model_id"`
	// Initial parameters for the pipeline.
	Params *Params `json:"params,omitempty"`
}

func (l LiveVideoToVideoParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LiveVideoToVideoParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *LiveVideoToVideoParams) GetSubscribeURL() string {
	if o == nil {
		return ""
	}
	return o.SubscribeURL
}

func (o *LiveVideoToVideoParams) GetPublishURL() string {
	if o == nil {
		return ""
	}
	return o.PublishURL
}

func (o *LiveVideoToVideoParams) GetControlURL() *string {
	if o == nil {
		return nil
	}
	return o.ControlURL
}

func (o *LiveVideoToVideoParams) GetEventsURL() *string {
	if o == nil {
		return nil
	}
	return o.EventsURL
}

func (o *LiveVideoToVideoParams) GetModelID() *string {
	if o == nil {
		return nil
	}
	return o.ModelID
}

func (o *LiveVideoToVideoParams) GetParams() *Params {
	if o == nil {
		return nil
	}
	return o.Params
}
