// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LLMMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (o *LLMMessage) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}

func (o *LLMMessage) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
