// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LLMTokenUsage struct {
	PromptTokens     int64 `json:"prompt_tokens"`
	CompletionTokens int64 `json:"completion_tokens"`
	TotalTokens      int64 `json:"total_tokens"`
}

func (o *LLMTokenUsage) GetPromptTokens() int64 {
	if o == nil {
		return 0
	}
	return o.PromptTokens
}

func (o *LLMTokenUsage) GetCompletionTokens() int64 {
	if o == nil {
		return 0
	}
	return o.CompletionTokens
}

func (o *LLMTokenUsage) GetTotalTokens() int64 {
	if o == nil {
		return 0
	}
	return o.TotalTokens
}
