// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Media struct {
	URL  string `json:"url"`
	Seed int64  `json:"seed"`
	Nsfw bool   `json:"nsfw"`
}

func (o *Media) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *Media) GetSeed() int64 {
	if o == nil {
		return 0
	}
	return o.Seed
}

func (o *Media) GetNsfw() bool {
	if o == nil {
		return false
	}
	return o.Nsfw
}
