// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MediaURL - A URL from which media can be accessed.
type MediaURL struct {
	// The URL where the media can be accessed.
	URL string `json:"url"`
}

func (o *MediaURL) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
