workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    livepeerai-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/livepeer/ai-worker/main/runner/gateway.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/livepeer-8mq/livepeer-ai/livepeerai-oas
targets:
    livepeerai-go:
        target: go
        source: livepeerai-OAS
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/livepeer-8mq/livepeer-ai/code-samples-go-livepeerai-go
